### ISSUE TITLE
Support in Centos7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [grondo/pdsh#67]
```
Support pdsh in centos7

```

Original issue reported on code.google.com by `subin....@gmail.com` on 3 Nov 2014 at 12:42

**Comment by igormp** [comment]
I've been running pdsh without a problem in Centos7 (both running from it and to other Centos7 hosts), so I think this old issue could probably be closed.

```
─▪pdsh -V && rpm --query centos-release              
pdsh-2.31 (+readline+debug)
rcmd modules: rsh,exec (default: rsh)
misc modules: (none)
centos-release-7-3.1611.el7.centos.x86_64
```

**Comment by grondo** [comment]
Great thanks!
