### ISSUE TITLE
dshbak eats output from hostname "0"

### ISSUE THREAD

**Issue by garlick** [grondo/pdsh#70]
Who can resist that donut shaped number?
```
$ dshbak -c <<EOT
0: foo
0: bar
1: foo
1: bar
2: foo
2: bar
EOT
----------------
[1-2]
----------------
foo
bar
```
This is pdsh-2.30.

**Comment by grondo** [comment]
Are you sure we should fix this? hostname `0` does not comply with recommendations in [rfc 1178](http://tools.ietf.org/html/rfc1178)

I propose we drop `dshbak` into interactive mode on encountering hostname "0", e.g.\
```
$ dshbak -c <<EOT
0: foo
0: bar
1: foo
1: bar
2: foo
2: bar
EOT
dshbak: a potentially unadvised hostname ['0'] has been encountered. Are you sure you wish to continue?
dshbak: Answer "yes" to continue: y
dshbak: Please answer "yes", "no", or "I'm not sure": yes
dshbak: Ok, continuing...
dshbak: a potentially unadvised hostname ['0'] has been encountered. Are you sure you wish to continue?
dshbak: Answer "yes" to continue: yes
----------------
[1-2]
----------------
foo
bar
```

We can create a `pdsh` plugin system to handle the case where user answers `I'm not sure`

**Comment by garlick** [comment]
Its OK I'll change my hostname to "lim 1/x, x->infintiy".  That's in your face with CALCULUS m.f.!

**Comment by grondo** [comment]
Can you try out the "fix" in branch [garlick-1-dshbak-0](https://github.com/grondo/pdsh/commits/garlick-1-dshbak-0)?

**Comment by garlick** [comment]
Works for me!
