### ISSUE TITLE
64bit-portability-issue

### ISSUE THREAD

**Issue by JohnWestlund** [grondo/pdsh#73]
I'm not sure why this is only getting called out in `nodeattr.c` since virtually the same line is used in several modules that I'm building.

```
[  100s] I: Program is likely to break with new gcc. Try -fno-strict-aliasing.
[  100s] W: pdsh-ohpc strict-aliasing-punning privsep.c:153, 201
[  100s] E: pdsh-ohpc 64bit-portability-issue nodeattr.c:149, 158, 161
```

The referenced lines:

```
src/modules/nodeattr.c:149:        excllist = list_split_append (excllist, ",", "pdsh_all_skip");
src/modules/nodeattr.c:158:		attrlist = list_split_append (attrlist, ",", arg);
src/modules/nodeattr.c:161:		excllist = list_split_append (excllist, ",", arg);
```

Looks to match the prototype of the function correctly.

**Comment by grondo** [comment]
Thanks @JohnWestlund!

What's the GCC version being used here?

**Comment by JohnWestlund** [comment]
@grondo out of SLES12: gcc-4.8-6.189

**Comment by JohnWestlund** [comment]
Swapped in gcc 5.2.0 and got the same result:

```
[   52s] I: Program is likely to break with new gcc. Try -fno-strict-aliasing.
[   52s] W: pdsh-ohpc strict-aliasing-punning privsep.c:153, 201
[   52s] E: pdsh-ohpc 64bit-portability-issue nodeattr.c:149, 158, 161
```

**Comment by grondo** [comment]
Ok, this warning is due to a missing include in `nodeattr.c`, so `list_split_append` return type defaulted to `int`.

Try the fix in 954331097da5b1319c30e9403bcf9ddcb4c7e7e2.

Also, is `nodeattr` module actually being used? I was thinking it should be deprecated in favor of `genders` module, which uses libgenders.

**Comment by grondo** [comment]
I've also pushed a potential fix for the type-punning warning in `privsep.c`.

**Comment by JohnWestlund** [comment]
@ grondo -- that fixed it. Thanks! I'm pushing to move to the genders module, but I'm trying to provide options.

**Comment by grondo** [comment]
Thanks. I'll merge this into master soon.
