### ISSUE TITLE
Alpine linux support?

### ISSUE THREAD

**Issue by clemenko** [grondo/pdsh#74]
I am trying to compile pdsh in alpine linux for use as a simple docker container. And I am running into a compile error. 

Here are my steps :

cd /opt/
git clone https://github.com/grondo/pdsh.git
docker run --rm -it -v /opt/pdsh:/opt/pdsh -v /opt/out:/opt/out alpine sh

#inside the container : 
apk add --update-cache make gcc g++
./configure --without-rsh --with-ssh --with-genders
make

make output: 
/opt/pdsh # make
make  all-recursive
make[1]: Entering directory '/opt/pdsh'
Making all in src
make[2]: Entering directory '/opt/pdsh/src'
Making all in common
make[3]: Entering directory '/opt/pdsh/src/common'
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT err.lo -MD -MP -MF ".deps/err.Tpo" -c -o err.lo err.c; \
then mv -f ".deps/err.Tpo" ".deps/err.Plo"; else rm -f ".deps/err.Tpo"; exit 1; fi
mkdir .libs
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT err.lo -MD -MP -MF .deps/err.Tpo -c err.c  -fPIC -DPIC -o .libs/err.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT err.lo -MD -MP -MF .deps/err.Tpo -c err.c -o err.o >/dev/null 2>&1
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT fd.lo -MD -MP -MF ".deps/fd.Tpo" -c -o fd.lo fd.c; \
then mv -f ".deps/fd.Tpo" ".deps/fd.Plo"; else rm -f ".deps/fd.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT fd.lo -MD -MP -MF .deps/fd.Tpo -c fd.c  -fPIC -DPIC -o .libs/fd.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT fd.lo -MD -MP -MF .deps/fd.Tpo -c fd.c -o fd.o >/dev/null 2>&1
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT hostlist.lo -MD -MP -MF ".deps/hostlist.Tpo" -c -o hostlist.lo hostlist.c; \
then mv -f ".deps/hostlist.Tpo" ".deps/hostlist.Plo"; else rm -f ".deps/hostlist.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT hostlist.lo -MD -MP -MF .deps/hostlist.Tpo -c hostlist.c  -fPIC -DPIC -o .libs/hostlist.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT hostlist.lo -MD -MP -MF .deps/hostlist.Tpo -c hostlist.c -o hostlist.o >/dev/null 2>&1
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT list.lo -MD -MP -MF ".deps/list.Tpo" -c -o list.lo list.c; \
then mv -f ".deps/list.Tpo" ".deps/list.Plo"; else rm -f ".deps/list.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT list.lo -MD -MP -MF .deps/list.Tpo -c list.c  -fPIC -DPIC -o .libs/list.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT list.lo -MD -MP -MF .deps/list.Tpo -c list.c -o list.o >/dev/null 2>&1
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT split.lo -MD -MP -MF ".deps/split.Tpo" -c -o split.lo split.c; \
then mv -f ".deps/split.Tpo" ".deps/split.Plo"; else rm -f ".deps/split.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT split.lo -MD -MP -MF .deps/split.Tpo -c split.c  -fPIC -DPIC -o .libs/split.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT split.lo -MD -MP -MF .deps/split.Tpo -c split.c -o split.o >/dev/null 2>&1
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT xmalloc.lo -MD -MP -MF ".deps/xmalloc.Tpo" -c -o xmalloc.lo xmalloc.c; \
then mv -f ".deps/xmalloc.Tpo" ".deps/xmalloc.Plo"; else rm -f ".deps/xmalloc.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT xmalloc.lo -MD -MP -MF .deps/xmalloc.Tpo -c xmalloc.c  -fPIC -DPIC -o .libs/xmalloc.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT xmalloc.lo -MD -MP -MF .deps/xmalloc.Tpo -c xmalloc.c -o xmalloc.o >/dev/null 2>&1
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT xpoll.lo -MD -MP -MF ".deps/xpoll.Tpo" -c -o xpoll.lo xpoll.c; \
then mv -f ".deps/xpoll.Tpo" ".deps/xpoll.Plo"; else rm -f ".deps/xpoll.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT xpoll.lo -MD -MP -MF .deps/xpoll.Tpo -c xpoll.c  -fPIC -DPIC -o .libs/xpoll.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT xpoll.lo -MD -MP -MF .deps/xpoll.Tpo -c xpoll.c -o xpoll.o >/dev/null 2>&1
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT xstring.lo -MD -MP -MF ".deps/xstring.Tpo" -c -o xstring.lo xstring.c; \
then mv -f ".deps/xstring.Tpo" ".deps/xstring.Plo"; else rm -f ".deps/xstring.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT xstring.lo -MD -MP -MF .deps/xstring.Tpo -c xstring.c  -fPIC -DPIC -o .libs/xstring.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT xstring.lo -MD -MP -MF .deps/xstring.Tpo -c xstring.c -o xstring.o >/dev/null 2>&1
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT pipecmd.lo -MD -MP -MF ".deps/pipecmd.Tpo" -c -o pipecmd.lo pipecmd.c; \
then mv -f ".deps/pipecmd.Tpo" ".deps/pipecmd.Plo"; else rm -f ".deps/pipecmd.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT pipecmd.lo -MD -MP -MF .deps/pipecmd.Tpo -c pipecmd.c  -fPIC -DPIC -o .libs/pipecmd.o
pipecmd.c: In function 'pipecmd_format_arg':
pipecmd.c:96:17: warning: variable 'q' set but not used [-Wunused-but-set-variable]
     const char *q, *p;
                 ^
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT pipecmd.lo -MD -MP -MF .deps/pipecmd.Tpo -c pipecmd.c -o pipecmd.o >/dev/null 2>&1
/bin/sh ../../libtool --tag=CC --mode=link gcc  -O3 -Wall -fno-strict-aliasing  -s  -o libcommon.la   err.lo fd.lo hostlist.lo list.lo split.lo xmalloc.lo xpoll.lo xstring.lo pipecmd.lo  
ar cru .libs/libcommon.a .libs/err.o .libs/fd.o .libs/hostlist.o .libs/list.o .libs/split.o .libs/xmalloc.o .libs/xpoll.o .libs/xstring.o .libs/pipecmd.o
ranlib .libs/libcommon.a
creating libcommon.la
(cd .libs && rm -f libcommon.la && ln -s ../libcommon.la libcommon.la)
make[3]: Leaving directory '/opt/pdsh/src/common'
Making all in qsnet
make[3]: Entering directory '/opt/pdsh/src/qsnet'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/opt/pdsh/src/qsnet'
Making all in modules
make[3]: Entering directory '/opt/pdsh/src/modules'
(echo  "{ global:";                \
 echo "    pdsh_module_info;";     \
 echo "    pdsh_module_priority;"; \
 echo "  local: *;";               \
 echo "};") > version.map
make  all-am
make[4]: Entering directory '/opt/pdsh/src/modules'
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT sshcmd.lo -MD -MP -MF ".deps/sshcmd.Tpo" -c -o sshcmd.lo sshcmd.c; \
then mv -f ".deps/sshcmd.Tpo" ".deps/sshcmd.Plo"; else rm -f ".deps/sshcmd.Tpo"; exit 1; fi
mkdir .libs
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT sshcmd.lo -MD -MP -MF .deps/sshcmd.Tpo -c sshcmd.c  -fPIC -DPIC -o .libs/sshcmd.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT sshcmd.lo -MD -MP -MF .deps/sshcmd.Tpo -c sshcmd.c -o sshcmd.o >/dev/null 2>&1
/bin/sh ../../libtool --tag=CC --mode=link gcc  -O3 -Wall -fno-strict-aliasing  -s  -o sshcmd.la -rpath /usr/local/lib/pdsh -module -avoid-version -Wl,--version-script=version.map sshcmd.lo  
gcc -shared  .libs/sshcmd.o   -Wl,--version-script=version.map -Wl,-soname -Wl,sshcmd.so -o .libs/sshcmd.so
ar cru .libs/sshcmd.a  sshcmd.o
ranlib .libs/sshcmd.a
creating sshcmd.la
(cd .libs && rm -f sshcmd.la && ln -s ../sshcmd.la sshcmd.la)
if /bin/sh ../../libtool --tag=CC --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT execcmd.lo -MD -MP -MF ".deps/execcmd.Tpo" -c -o execcmd.lo execcmd.c; \
then mv -f ".deps/execcmd.Tpo" ".deps/execcmd.Plo"; else rm -f ".deps/execcmd.Tpo"; exit 1; fi
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT execcmd.lo -MD -MP -MF .deps/execcmd.Tpo -c execcmd.c  -fPIC -DPIC -o .libs/execcmd.o
 gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../.. -O3 -Wall -fno-strict-aliasing -MT execcmd.lo -MD -MP -MF .deps/execcmd.Tpo -c execcmd.c -o execcmd.o >/dev/null 2>&1
/bin/sh ../../libtool --tag=CC --mode=link gcc  -O3 -Wall -fno-strict-aliasing  -s  -o execcmd.la -rpath /usr/local/lib/pdsh -module -avoid-version -Wl,--version-script=version.map execcmd.lo  
gcc -shared  .libs/execcmd.o   -Wl,--version-script=version.map -Wl,-soname -Wl,execcmd.so -o .libs/execcmd.so
ar cru .libs/execcmd.a  execcmd.o
ranlib .libs/execcmd.a
creating execcmd.la
(cd .libs && rm -f execcmd.la && ln -s ../execcmd.la execcmd.la)
make[4]: Leaving directory '/opt/pdsh/src/modules'
make[3]: Leaving directory '/opt/pdsh/src/modules'
Making all in pdsh
make[3]: Entering directory '/opt/pdsh/src/pdsh'
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT main.o -MD -MP -MF ".deps/main.Tpo" -c -o main.o main.c; \
then mv -f ".deps/main.Tpo" ".deps/main.Po"; else rm -f ".deps/main.Tpo"; exit 1; fi
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT dsh.o -MD -MP -MF ".deps/dsh.Tpo" -c -o dsh.o dsh.c; \
then mv -f ".deps/dsh.Tpo" ".deps/dsh.Po"; else rm -f ".deps/dsh.Tpo"; exit 1; fi
In file included from dsh.c:68:0:
/usr/include/sys/poll.h:1:2: warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]
 #warning redirecting incorrect #include <sys/poll.h> to <poll.h>
  ^
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT mod.o -MD -MP -MF ".deps/mod.Tpo" -c -o mod.o mod.c; \
then mv -f ".deps/mod.Tpo" ".deps/mod.Po"; else rm -f ".deps/mod.Tpo"; exit 1; fi
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT rcmd.o -MD -MP -MF ".deps/rcmd.Tpo" -c -o rcmd.o rcmd.c; \
then mv -f ".deps/rcmd.Tpo" ".deps/rcmd.Po"; else rm -f ".deps/rcmd.Tpo"; exit 1; fi
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT opt.o -MD -MP -MF ".deps/opt.Tpo" -c -o opt.o opt.c; \
then mv -f ".deps/opt.Tpo" ".deps/opt.Po"; else rm -f ".deps/opt.Tpo"; exit 1; fi
opt.c: In function 'wcoll_expand':
opt.c:776:15: warning: passing argument 1 of 'free' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
         free (hosts);
               ^
In file included from opt.c:34:0:
/usr/include/stdlib.h:41:6: note: expected 'void *' but argument is of type 'const char *'
 void free (void *);
      ^
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT privsep.o -MD -MP -MF ".deps/privsep.Tpo" -c -o privsep.o privsep.c; \
then mv -f ".deps/privsep.Tpo" ".deps/privsep.Po"; else rm -f ".deps/privsep.Tpo"; exit 1; fi
privsep.c: In function 'p_rresvport_af':
privsep.c:218:9: warning: implicit declaration of function 'rresvport' [-Wimplicit-function-declaration]
  return rresvport (port);
         ^
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT pcp_server.o -MD -MP -MF ".deps/pcp_server.Tpo" -c -o pcp_server.o pcp_server.c; \
then mv -f ".deps/pcp_server.Tpo" ".deps/pcp_server.Po"; else rm -f ".deps/pcp_server.Tpo"; exit 1; fi
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT pcp_client.o -MD -MP -MF ".deps/pcp_client.Tpo" -c -o pcp_client.o pcp_client.c; \
then mv -f ".deps/pcp_client.Tpo" ".deps/pcp_client.Po"; else rm -f ".deps/pcp_client.Tpo"; exit 1; fi
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT testcase.o -MD -MP -MF ".deps/testcase.Tpo" -c -o testcase.o testcase.c; \
then mv -f ".deps/testcase.Tpo" ".deps/testcase.Po"; else rm -f ".deps/testcase.Tpo"; exit 1; fi
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT wcoll.o -MD -MP -MF ".deps/wcoll.Tpo" -c -o wcoll.o wcoll.c; \
then mv -f ".deps/wcoll.Tpo" ".deps/wcoll.Po"; else rm -f ".deps/wcoll.Tpo"; exit 1; fi
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT cbuf.o -MD -MP -MF ".deps/cbuf.Tpo" -c -o cbuf.o cbuf.c; \
then mv -f ".deps/cbuf.Tpo" ".deps/cbuf.Po"; else rm -f ".deps/cbuf.Tpo"; exit 1; fi
cbuf.c: In function 'cbuf_peek_line':
cbuf.c:668:15: warning: variable 'l' set but not used [-Wunused-but-set-variable]
     int n, m, l;
               ^
cbuf.c: In function 'cbuf_read_line':
cbuf.c:704:15: warning: variable 'l' set but not used [-Wunused-but-set-variable]
     int n, m, l;
               ^
cbuf.c: In function 'cbuf_replay_line':
cbuf.c:741:15: warning: variable 'l' set but not used [-Wunused-but-set-variable]
     int n, m, l;
               ^
cbuf.c: In function 'cbuf_write_line':
cbuf.c:815:23: warning: variable 'n' set but not used [-Wunused-but-set-variable]
     int nfree, ncopy, n;
                       ^
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT xpopen.o -MD -MP -MF ".deps/xpopen.Tpo" -c -o xpopen.o xpopen.c; \
then mv -f ".deps/xpopen.Tpo" ".deps/xpopen.Po"; else rm -f ".deps/xpopen.Tpo"; exit 1; fi
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT ltdl.o -MD -MP -MF ".deps/ltdl.Tpo" -c -o ltdl.o ltdl.c; \
then mv -f ".deps/ltdl.Tpo" ".deps/ltdl.Po"; else rm -f ".deps/ltdl.Tpo"; exit 1; fi
ltdl.c: In function 'try_dlopen':
ltdl.c:3207:14: warning: the address of 'sys_search_path' will always evaluate as 'true' [-Waddress]
    if (!file && sys_search_path)
              ^
ltdl.c: In function 'lt_dlopenext':
ltdl.h:89:24: warning: the address of 'archive_ext' will always evaluate as 'true' [-Waddress]
 #define LT_STRLEN(s) (((s) && (s)[0]) ? strlen (s) : 0)
                        ^
ltdl.c:246:48: note: in definition of macro 'LT_EMALLOC'
 #define LT_EMALLOC(tp, n) ((tp *) lt_emalloc ((n) * sizeof(tp)))
                                                ^
ltdl.c:3499:33: note: in expansion of macro 'LT_STRLEN'
   tmp = LT_EMALLOC (char, len + LT_STRLEN (archive_ext) + 1);
                                 ^
In file included from ltdl.c:129:0:
ltdl.h:89:24: warning: the address of 'shlib_ext' will always evaluate as 'true' [-Waddress]
 #define LT_STRLEN(s) (((s) && (s)[0]) ? strlen (s) : 0)
                        ^
ltdl.c:3520:7: note: in expansion of macro 'LT_STRLEN'
   if (LT_STRLEN (shlib_ext) > LT_STRLEN (archive_ext))
       ^
ltdl.h:89:24: warning: the address of 'archive_ext' will always evaluate as 'true' [-Waddress]
 #define LT_STRLEN(s) (((s) && (s)[0]) ? strlen (s) : 0)
                        ^
ltdl.c:3520:31: note: in expansion of macro 'LT_STRLEN'
   if (LT_STRLEN (shlib_ext) > LT_STRLEN (archive_ext))
                               ^
ltdl.h:89:24: warning: the address of 'shlib_ext' will always evaluate as 'true' [-Waddress]
 #define LT_STRLEN(s) (((s) && (s)[0]) ? strlen (s) : 0)
                        ^
ltdl.c:246:48: note: in definition of macro 'LT_EMALLOC'
 #define LT_EMALLOC(tp, n) ((tp *) lt_emalloc ((n) * sizeof(tp)))
                                                ^
ltdl.c:3523:37: note: in expansion of macro 'LT_STRLEN'
       tmp = LT_EMALLOC (char, len + LT_STRLEN (shlib_ext) + 1);
                                     ^
if gcc -DHAVE_CONFIG_H -I. -I. -I../.. -I../..    -O3 -Wall -fno-strict-aliasing -MT config.o -MD -MP -MF ".deps/config.Tpo" -c -o config.o config.c; \
then mv -f ".deps/config.Tpo" ".deps/config.Po"; else rm -f ".deps/config.Tpo"; exit 1; fi
/bin/sh ../../libtool --tag=CC --mode=link gcc  -O3 -Wall -fno-strict-aliasing  -s  -o pdsh.inst  -export-dynamic  ../../src/common/libcommon.la main.o dsh.o mod.o rcmd.o opt.o privsep.o pcp_server.o pcp_client.o testcase.o wcoll.o cbuf.o xpopen.o ltdl.o config.o  -ldl 
mkdir .libs
gcc -O3 -Wall -fno-strict-aliasing -s -o pdsh.inst main.o dsh.o mod.o rcmd.o opt.o privsep.o pcp_server.o pcp_client.o testcase.o wcoll.o cbuf.o xpopen.o ltdl.o config.o -Wl,--export-dynamic  ../../src/common/.libs/libcommon.a -ldl
privsep.o: In function `privsep_init':
privsep.c:(.text+0x1dd): undefined reference to `rresvport'
privsep.o: In function `privsep_rresvport_af':
privsep.c:(.text+0x4a7): undefined reference to `rresvport'
privsep.o: In function `privsep_rresvport':
privsep.c:(.text+0x671): undefined reference to `rresvport'
collect2: error: ld returned 1 exit status
Makefile:450: recipe for target 'pdsh.inst' failed
make[3]: *** [pdsh.inst] Error 1
make[3]: Leaving directory '/opt/pdsh/src/pdsh'
Makefile:354: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/opt/pdsh/src'
Makefile:403: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/pdsh'
Makefile:332: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by grondo** [comment]
Looks like definition for `rresvport` is missing at final link. On Red Hat and Ubuntu systems I spot checked this symbol is in `libc.so.6`, can you find the symbol on your system?
```
$ nm -D /lib/x86_64-linux-gnu/libc.so.6  | grep rresv
00000000001160a0 T rresvport
00000000001154c0 T rresvport_af
```

**Comment by grondo** [comment]
Actually the `privsep` code is only needed if you are installing pdsh setuid, which I'd guess is pretty uncommon. You could try commenting out or conditionally compiling the `privsep.c` into pdsh, and remove the `privsep_*` calls (or wrap them in `HAVE_PRIVSEP`) to get this compiled, or find the next issue.

**Comment by clemenko** [comment]
Is it possible to branch this for me? My dev is not that strong.

**Comment by grondo** [comment]
Ok, I tried pushing a quickfix on the `no-rresvport` branch. Check it out and let me know if it works. This should just disable the use of `rresvport(3)` and the unnecessary privsep code when it is not found. You may find other errors during compile though.

**Comment by clemenko** [comment]
New error : 
/opt/pdsh # make
make  all-recursive
make[1]: Entering directory '/opt/pdsh'
Making all in src
make[2]: Entering directory '/opt/pdsh/src'
Making all in common
make[3]: Entering directory '/opt/pdsh/src/common'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/opt/pdsh/src/common'
Making all in qsnet
make[3]: Entering directory '/opt/pdsh/src/qsnet'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/opt/pdsh/src/qsnet'
Making all in modules
make[3]: Entering directory '/opt/pdsh/src/modules'
make  all-am
make[4]: Entering directory '/opt/pdsh/src/modules'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/opt/pdsh/src/modules'
make[3]: Leaving directory '/opt/pdsh/src/modules'
Making all in pdsh
make[3]: Entering directory '/opt/pdsh/src/pdsh'
/bin/sh ../../libtool --tag=CC --mode=link gcc  -O3 -Wall -fno-strict-aliasing  -s  -o pdsh.inst  -export-dynamic  ../../src/common/libcommon.la main.o dsh.o mod.o rcmd.o opt.o privsep.o pcp_server.o pcp_client.o testcase.o wcoll.o cbuf.o xpopen.o ltdl.o config.o  -ldl 
gcc -O3 -Wall -fno-strict-aliasing -s -o pdsh.inst main.o dsh.o mod.o rcmd.o opt.o privsep.o pcp_server.o pcp_client.o testcase.o wcoll.o cbuf.o xpopen.o ltdl.o config.o -Wl,--export-dynamic  ../../src/common/.libs/libcommon.a -ldl
privsep.o: In function `privsep_init':
privsep.c:(.text+0x1dd): undefined reference to `rresvport'
privsep.o: In function `privsep_rresvport_af':
privsep.c:(.text+0x4a7): undefined reference to `rresvport'
privsep.o: In function `privsep_rresvport':
privsep.c:(.text+0x671): undefined reference to `rresvport'
collect2: error: ld returned 1 exit status
Makefile:450: recipe for target 'pdsh.inst' failed
make[3]: *** [pdsh.inst] Error 1
make[3]: Leaving directory '/opt/pdsh/src/pdsh'
Makefile:354: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/opt/pdsh/src'
Makefile:403: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/opt/pdsh'
Makefile:332: recipe for target 'all' failed
make: *** [all] Error 2
/opt/pdsh # 


Did you want to try and compile it under Alpine Linux?

**Comment by grondo** [comment]
This looks like the same error, are you sure you are on the `no-rresvport` branch? (run `git branch`)

**Comment by clemenko** [comment]
[root@dev pdsh]# git branch
  master
* origin/no-rresvport
[root@dev pdsh]#

**Comment by grondo** [comment]
Hm, ok. I'll try to build in alpine linux docker container if I have time later. In the meantime, try starting over with `./configure --without-rsh --with-ssh --with-genders && make clean && make`.

Also, just to make sure `grep RRESVPORT config.h` at the top level of the src to make sure configure found that `rresvport` is not available.

**Comment by clemenko** [comment]
[root@dev pdsh]# grep RRESVPORT config.h
/* #undef HAVE_RRESVPORT */
/* #undef HAVE_RRESVPORT_AF */

My build steps are to git clone and branch on a centos7 host. then start the alpine docker image : 
 docker run --rm -it -v /opt/pdsh:/opt/pdsh -v /opt/aout:/opt/out alpine sh
One in I "apk add --update-cache gcc g++ perl make" then configure as above and then make. 

thanks for the help. My goal is to have a pdsh docker image based on alpine. Maybe that is something you could output? Or even add a Dockerfile to your git repo?

**Comment by grondo** [comment]
Hm, following your instructions it worked for me. Here's a Dockerfile that passes `make check` at least for me. Thanks for the alpine linux instructions:
```
FROM alpine
RUN apk add --update-cache make gcc g++ perl git
RUN adduser -S pdsh
USER pdsh
RUN cd /tmp && git clone  --branch=no-rresvport https://github.com/grondo/pdsh
RUN cd /tmp/pdsh && ./configure --with-ssh && make  && make check
```

**Comment by clemenko** [comment]
That worked! Fantastic! THANKS!
