### ISSUE TITLE
urls pointing to old sites

### ISSUE THREAD

**Issue by chu11** [grondo/pdsh#76]
Friend noticed that the link at the bottom of the dshbak manpage still points to googlecode.  Was going to send a pull request with a fix, but noticed you didn't put any URLs in pdsh or pdcp, so perhaps you'd rather just delete the line?

Doing a big grep for 'http', noticed the links in the spec file still point to sourceforge.

**Comment by grondo** [comment]
Yeah, deleting sounds fine. Thanks!

**Comment by chu11** [comment]
merged in #77
