### ISSUE TITLE
Update autotools

### ISSUE THREAD

**Issue by grondo** [grondo/pdsh#79]
`pdsh` is long in need of an autotools update. Besides the likely hundereds of "deprecated" AC macro warnings, there are the following minor gotchas:
- Use of libtldl as a portable `dlopen()`. In the current code, and older libltdl is used that is a single drop-in `libltdl.[ch]` set of files. Newer libtoolize wants to copy an entire tree of files under `${top_srcdir}`/libltldl, along with its own autotools setup, etc.
- Currently products of ./bootstrap are committed to the repo. This made sense long ago, but now it is standard practice (and much cleaner) to not commit these products, so we should probably switch to that.

**Comment by tabaer** [comment]
I am developing a new module and have run afoul of both of these.

**Comment by grondo** [comment]
Ugh, sorry. If you have any success updating autotools feel free to share ;-)

One idea I had was to pull support for libtdl, and use straight dlopen/dlsym, which would solve bullet 1 above. The other bullet is much more tractable.

**Comment by tabaer** [comment]
I made an initial pass at both removing the bootstrap products from revision control and going directly to dlopen and friends in my fork (https://github.com/tabaer/pdsh).  I've gotten it to the point where it no longer segfaults at startup. :)
