### ISSUE TITLE
torque?

### ISSUE THREAD

**Issue by endocrantz** [grondo/pdsh#80]
even though we configure with --with-torque it does not produce a module, and no -j option available

No such rcmd module "torque"

invalid option -- 'j'

**Comment by grondo** [comment]
I assume the torque module does not appear in the output of `pdsh -V`?

If not, what is the output of `./configure`? I didn't write it, but it appears that torque configure checks for `pbs-config`, and if it doesn't exist, the build of torque module is skipped.

**Comment by endocrantz** [comment]
I was able to get --with-torque to pass in configure (patch below) but something up with libtool :
ranlib .libs/torque.a
creating torque.la
/bin/sed: can't read /usr/local/lib/libhwloc.la: No such file or directory

from src/modules/torque.la
dependency_libs=' /opt/pbs/lib64/libtorque.la -lz -ldl -lcrypto -lssl -lpthread -lrt -L/usr/local/lib /usr/local/lib/libhwloc.la -lxml2 -L/opt/pbs/lib64'

Running make again completes the build, and the module(s) work fine. My configure options:
./configure --with-ssh --with-torque --with-readline --without-rsh --without-pam --libdir=/opt/pbs/lib64 --prefix=/

The patch below for configure worked to get the torque compile of conftest to work. Torque libraries are not in a standard location. You may wish to do it differently. Adding  --libdir= was not sufficient for conftest,, but required during the module build. The -ltorque was defined twice, once in TORQUE_LIBS and once statically, so I omitted the static below.
pbs-config --libadd 
-L/opt/pbs/lib64

Thanks you for your efforts, suggestions welcome, Andy

 git diff
diff --git a/configure b/configure
index 05a8945..fd7e560 100755
--- a/configure
+++ b/configure
@@ -26478,7 +26478,7 @@ echo "${ECHO_T}${ac_with_torque=no}" >&6

   if test "$ac_with_torque" = "yes"; then
     if pbs-config 1>/dev/null 2>&1; then
-      TORQUE_LIBS=$(pbs-config --libs)
+      TORQUE_LIBS=$(pbs-config --libs --libadd)
       TORQUE_CPPFLAGS=$(pbs-config --cflags)
       saveLIBS="$LIBS"
       LIBS="$TORQUE_LIBS $LIBS"
@@ -26488,7 +26488,7 @@ if test "${ac_cv_lib_torque_pbs_connect+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-ltorque  $LIBS"
+LIBS="$LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF

**Comment by endocrantz** [comment]
That diff is messed up! Not sure what I did. I've left the static -ltorque in for this:

git diff
diff --git a/configure b/configure
index 05a8945..1a5ee01 100755
--- a/configure
+++ b/configure
@@ -26478,7 +26478,7 @@ echo "${ECHO_T}${ac_with_torque=no}" >&6

   if test "$ac_with_torque" = "yes"; then
     if pbs-config 1>/dev/null 2>&1; then
-      TORQUE_LIBS=$(pbs-config --libs)
+      TORQUE_LIBS=$(pbs-config --libs --libadd)
       TORQUE_CPPFLAGS=$(pbs-config --cflags)
       saveLIBS="$LIBS"
       LIBS="$TORQUE_LIBS $LIBS"

**Comment by grondo** [comment]
Thanks would you mind posting your solution as a PR?

**Comment by endocrantz** [comment]
Sure, but I still have a libtool problem where it is trying to sed /usr/local/lib/libhwloc.la although it doesn't exist. I did not come up with a solution for that.

Appreciate your efforts

**Comment by grondo** [comment]
hm, I wonder what `pbs-config --libs` reports.

More modern way to get this info is with pkg-config, do you know if torque development libs supports pkg-config?

**Comment by endocrantz** [comment]
pbs-config --libs returns -ltorque 
while
pbs-config --libadd returns -L/correct/path/lib

There is a static -ltorque added to LIBS later that seemed unnecessary, but could be conditional.

I do not see a .pc file anywhere for torque, sorry

**Comment by endocrantz** [comment]
/opt/pbs/lib64/libtorque.la contained dependency_libs including"-L/usr/local/lib /usr/local/lib/libhwloc.la" which would be wrong. Removing those references allows pdsh to build with torque cleanly now, and works well, so far.  I used:
./configure --with-ssh --with-torque --with-readline --without-rsh --without-pam

Thank you again for your efforts, Andy

**Comment by grondo** [comment]
OK, so no need for PR #81 anymore?

**Comment by endocrantz** [comment]
PR #81 patch fixed the configure, then I could build after fixing the installed version of torque's libtool-dependency error.

Thank you Mark, I think we're all set with PR #81 now.
