### ISSUE TITLE
echo fqdn at output

### ISSUE THREAD

**Issue by jkrauska** [grondo/pdsh#84]
I have servers in different datacenters with the same basename and want to run operations on all of them using pdsh.

eg. 
server001.dc1 and
server001.dc2

The output from pdsh just surports server001 for both.

pdsh -w server001.dc[1-2] hostname
server001: server001.dc1.example.com
server001: server002.dc1.example.com

Couldn't find an easy flag to use full provided name.

**Comment by jkrauska** [comment]
typo

**Comment by grondo** [comment]
pdsh should only strip domain names from hosts when all host domains are the same. Note for the command above the domain name of both hosts is `.dc1.example.com`, perhaps the argument to `-w` needs to be quoted?

If you need a way to keep domain names in output when they are all the same, we'll perhaps have to add a new option (can't remember if there is already one, but I didn't find it on quick examination)

**Comment by jkrauska** [comment]
@grondo found the root cause.

was specifying -w server001 -w server001.dc2
(dc1 was my first dc, so I've gotten lazy about not using it in names)

The above was outputting just 'server001'.
When I added the subdomain to the firstpart, my output now has subdomains.

Thanks.

Close?

**Comment by grondo** [comment]
Thanks!
