### ISSUE TITLE
PDSH_USER?

### ISSUE THREAD

**Issue by dtaht** [grondo/pdsh#86]
I have used pdsh for years and years, and I'm delighted to see it being maintained now in git.

I am curious as to the "rightest way" to specify the user for ssh? 

Me, I'm perpetually doing finger foo, and not specifying -l whoever, and when you do that to yourself on 30 machines and ssh pops up 30 windows, it's a PITA.

I can always go and produce a patch for an PDSH_USER variable.

**Comment by grondo** [comment]
If you are always using the same remote user to connect to a host with `ssh`, probably the most correct way is to set the `User` option for that host or host(s) in your `.ssh/config`. See this [stackoverflow](https://stackoverflow.com/questions/10197559/ssh-configuration-override-the-default-username) answer for example.

In general , I wouldn't be opposed to a patch with a PDSH_USER or PDSH_RCMD_USER variable, that seems pretty straightforward and akin to options like `-R` having their default set by PDSH_RCMD_TYPE, if it is in the environment.

**Comment by dtaht** [comment]
I've used that before, and it works for individual ssh sessions. But for some reason pdsh doesn't pick it up.

Example config: 

d@dancer:~/.ssh$ more config 
Host chip*
	User root
Host gw*
	User root

As I typically have two users (one root, one normal) and switch between them a lot, hmm, well PDSH_RCMD_USER makes more sense. I'll roll a patch at some point (now that there's a place to send patches to!)

**Comment by grondo** [comment]
I wonder if the ssh config doesn't work because the sshcmd module always adds `-l` or equivalent option, thus overriding the ssh config, even when username is not being overridden on command line or via `rcmd_type:user@host` syntax. That does seem a bit like a bug to me...

**Comment by dtaht** [comment]
Well, actually - I pulled your latest tree from git, intending to add this feature, built it - and my default ssh config worked. (I was using 2.26 before) When's the next release? :) 

Thx so much for putting this code more "out there". I think I need to go get it running directly on lede-project again.

Has the readline issue ever been resolved? Things like debian build pdsh without it....
